## Chapter 7 - Angular Momentum and Rotation

In [1]:
from numpy import sqrt, pi, exp, angle
from qutip import *

Our usual spin operators (spin-1/2)

In [2]:
pz = basis(2,0)
mz = basis(2,1)
px = 1/sqrt(2)*(pz + mz)
mx = 1/sqrt(2)*(pz - mz)
py = 1/sqrt(2)*(pz + 1j*mz)
my = 1/sqrt(2)*(pz - 1j*mz)
Sx = 1/2.0*sigmax()
Sy = 1/2.0*sigmay()
Sz = 1/2.0*sigmaz()
Splus = Sx + 1j*Sy
Sminus = Sx - 1j*Sy

In [14]:
Splus*pz

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.]
 [ 0.]]

In [15]:
Splus*mz

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 1.]
 [ 0.]]

Define the spin-1 operators. We use J just to keep them apart. Could be S instead.

In [3]:
Jx = 1/sqrt(2)*Qobj([[0,1,0],[1,0,1],[0,1,0]])
Jy = 1/sqrt(2)*Qobj([[0,-1j,0],[1j,0,-1j],[0,1j,0]])
Jz = Qobj([[1,0,0],[0,0,0],[0,0,-1]])
Jplus = Jx + 1j*Jy
Jminus = Jx - 1j*Jy

## Rotations of spin-1/2

In [4]:
Rz90 = (-1j*pi/2*Sz).expm()

In [5]:
Rz90

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = False
Qobj data =
[[ 0.70710678-0.70710678j  0.00000000+0.j        ]
 [ 0.00000000+0.j          0.70710678+0.70710678j]]

In [6]:
Rz90*px

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.5-0.5j]
 [ 0.5+0.5j]]

Doesn't look like example 7.4 because it's not simplified. How to check:

In [7]:
exp(-1j*pi/4)*py

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.5-0.5j]
 [ 0.5+0.5j]]

 Yes, this agrees.

Can also use inner product:

In [8]:
mx.dag()*Rz90*px

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = False
Qobj data =
[[ 0.-0.70710678j]]

In [9]:
angle(0.707 - 0.707j) == -pi/4

True

## Find the spin-1 states (the eigenstates of the corresponding matrix)
According to the postulates, the allowed values of an observable are the eigenvalues with corresponding eigenstates.

We know the matrix representation of Jx, Jy, Jz in the Z-basis so we can find all 9 states (in the Z basis). Why nine? There are three possible values $\hbar$, 0, $-\hbar$ for each of three directions.

In [10]:
yevals, (yd,y0,yu) = Jy.eigenstates()
zevals, (zd,z0,zu) = Jz.eigenstates()
xevals, (xd,x0,xu) = Jx.eigenstates()
xd = -xd  # fix the signs to match book
yu = -yu  # fix the signs to match book

In [11]:
y0

Quantum object: dims = [[3], [1]], shape = [3, 1], type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.70710678]]

In [40]:
Rz90 = (-1j*pi/2*Jz).expm()

In [41]:
Rz90*x0

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.-0.70710678j]
 [0.+0.j        ]
 [0.-0.70710678j]]

In [24]:
y0

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.70710678]]

In [25]:
xu

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.5       ]
 [0.70710678]
 [0.5       ]]

### 7.10 A spin-1 particle is measured to have $S_y=\hbar$. What is the probability that a subsequent measurement will yield $S_z=0$? $S_z=\hbar$? $S_z=-\hbar$?

In [56]:
(z0.dag()*yu).norm()**2

0.4999999999999999